services:
  - type: web
    name: school-management-backend
    runtime: node
    rootDir: school-management-system/server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000